# Generated by Django 5.2.5 on 2025-08-12 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birthdate', models.DateTimeField()),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.singer')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('genre', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.album')),
            ],
        ),
    ]
